const recipes = [
    {
        recipeId: 0,
        SentenceAim: undefined,
        Keyword: undefined,
        ToV: undefined,
        Actions: undefined,
        TagAnimal: undefined,
        TagDistribution: undefined,
        TagEnergy: undefined,
        TagFood: undefined,
        TagManagement: undefined,
        TagWaste: undefined,
    },
    {
        recipeId: 1,
        SentenceAim: 'take action',
        Keyword: 'impact',
        ToV: undefined,
        Actions: 'TRUE',
        TagAnimal: undefined,
        TagDistribution: undefined,
        TagEnergy: undefined,
        TagFood: undefined,
        TagManagement: undefined,
        TagWaste: undefined,
    },
    {
        recipeId: 2,
        SentenceAim: 'dissemination',
        Keyword: 'recycle',
        ToV: undefined,
        Actions: 'FALSE',
        TagAnimal: undefined,
        TagDistribution: undefined,
        TagEnergy: undefined,
        TagFood: undefined,
        TagManagement: undefined,
        TagWaste: undefined,
    },
    {
        recipeId:3,
        SentenceAim: 'take action',
        Keyword: 'greenhouse gas',
        ToV: 'FALSE',
        Actions: 'FALSE',
        TagAnimal: undefined,
        TagDistribution: undefined,
        TagEnergy: undefined,
        TagFood: undefined,
        TagManagement: undefined,
        TagWaste: undefined,
    }
]