const recipes = [

    {  
        recipeId: 0,
        title: 'Double recycle goals burger',
        desc: '“For those who love environment and composting, created to provide your daily dose of pro-active attitude but with a strong lack of evidence.”',
        Keyword: 'environmental',
        Actions: undefined,
        Animal: undefined,
        Distribution: undefined,
        Energy: undefined,
        Food: undefined,
        Management: 'TRUE',
        Waste: 'TRUE',
        Evidence: 'FALSE',
        Aim: 'take action',
        TaPerc: '60',
        GrPerc: '11',
        StatisticText: '“Recycling Goals Burger is back Double”. For those who love environment and composting, the Double Globe Warming Burger is here for you. Created by taking in consideration both Waste and Management, it was possible to select the most nourishing keyword as its main ingredient: Environmental. It provides your daily dose of pro-active attitude (60% take action) but with a strong lack of evidence (just 11% of contexts is providing actual data). It’s like the classic, but greener.'
    },
    {  
        recipeId: 1,
        title: 'Deluxe recy-pounder',
        desc: '“If you thrive for recycling, this is the meal for you: it grants an unforgettable taste with a dynamic approach, supported by high levels of groundless data.”',
        Keyword: 'environmental',
        Actions: 'TRUE',
        Animal: undefined,
        Distribution: undefined,
        Energy: undefined,
        Food: undefined,
        Management: undefined,
        Waste: 'TRUE',
        Evidence: 'FALSE',
        Aim: 'take action',
        TaPerc: '66',
        GrPerc: '15',
        StatisticText: '“Because you deserve to be recycled in the best way”. If you thrive for cleaner environment and recycling, this is the right thing for you. With the indispensable ingredient Environmental, this mixture gives the opportunity to bite Waste and Action granting you an unforgettable taste. Deluxe Recy-pounder provides to you a good amount of dynamic approach (66% take action) but as well as high percentage of groundless data (only 15% of contexts is containing accurate data). Ready to try it?'
    },
    {  
        recipeId: 2,
        title: 'Smoky forest burger',
        desc: '“Food is delicious. Sources are scarce. A win-win situation is all that we have left. Its smoky flavour bestows immense knowledge, but slim analytical data”',
        Keyword: 'responsibility',
        Actions: undefined,
        Animal: undefined,
        Distribution: undefined,
        Energy: undefined,
        Food: 'TRUE',
        Management: 'TRUE',
        Waste: undefined,
        Evidence: 'FALSE',
        Aim: 'dissemination',
        TaPerc: '45',
        GrPerc: '14',
        StatisticText:'“Blessed by the tree gods”. Food is delicious. Sources are scarce. A win-win situation is all that we have left. Its smoky flavour was obtained by burning the finest stumps of Food and Management. Filled with high quality Responsibility, this fancy and reliable burger bestows its eaters a 55% of disseminated knowledge, but also features a slim 14% of precise analytical data. A commitment to Mother Nature and her precious soil.'
    },
    {  
        recipeId: 3,
        title: 'Zero CO2 big Wrap',
        desc: '“The freshness of the purest is what makes this wrap so unique! Its dissemination statements allow you to sustain a healthy and balanced diet without added evidence.”',
        Keyword: 'planet',
        Actions: undefined,
        Animal: undefined,
        Distribution: undefined,
        Energy: 'TRUE',
        Food: undefined,
        Management: 'TRUE',
        Waste: undefined,
        Evidence: 'FALSE',
        Aim:  'dissemination',
        TaPerc: '48',
        GrPerc: '6',
        StatisticText: '“The Freshness Of Oxygen, Wrapped Up For You”. The freshness of the purest Planet is what makes Zero CO2 Wrap unique of its kind! The Energy Resourcing and Management-based sauce give it the flavour that has caught the attention of our customers. Plus with its 52% of dissemination statements it allows you to sustain a healthy and balanced diet without added evidence (92% groundless).'
    },
    {  
        recipeId: 4,
        title: 'Quarter earth burger',
        desc: '“The best fit for you if you put your heart and mind in what you believe in! It grants outstanding educational information and even more overwhelming idle evidences.”',
        Keyword: 'impact',
        Actions: 'TRUE',
        Animal: undefined,
        Distribution: undefined,
        Energy: undefined,
        Food: undefined,
        Management: 'TRUE',
        Waste: undefined,
        Evidence: 'FALSE',
        Aim: 'dissemination',
        TaPerc: '26',
        GrPerc: '4',
        StatisticText:'“This Lip-smacking Deliciousness Won’t Betray Your Planet”. Is one of your goals trying to put your heart and mind in what you believe in? Then, the Quarter Earth Pounder is the best fit for you! Its conscious recipe relies on Actions and Management, but is mainly supported by the Impact you want to make. It grants an outstanding 74% of educational information and even more overwhelming idle evidences, reaching 96% of all contexts. Hope-filled promises with not-so-clear premises.'
    },
    {  
        recipeId: 5,
        title: 'Spicy planet-saver wrap',
        desc: '“This one is ready to burn your tongue. Prepared with the spiciest ingredient of all, its nourishment will grant information and not-so incredible data. Recommended by our chef Lumière the Lobstèr.”',
        Keyword: 'sustainability',
        Actions: 'TRUE',
        Animal: undefined,
        Distribution: undefined,
        Energy: undefined,
        Food: 'TRUE',
        Management: undefined,
        Waste: undefined,
        Evidence: 'FALSE',
        Aim: 'dissemination',
        TaPerc: '46',
        GrPerc: ' 13',
        StatisticText: '“For the hot ones”.  This seasoned combo of Food and Action are ready to burn your tongue. And if you still think it is not piquant enough, don’t worry because we prepared the spiciest ingredient of all:  Sustainability. The nourishment is granted with 54% of dissemination and incredible 87% of groundless data. Spicy Planet-saver Burger is one of the flavorsome burger you’ll ever try. Recommended by our chef Lumiere Lobster.'
    },
    {  
        recipeId: 6,
        title: 'Crispy animal-welfare burger',
        desc: '“A custom-made meal for livestock rights activists that proposes many purposed-filled intentions and a huge amount of groundless information.”',
        Keyword: 'sustainability',
        Actions: undefined,
        Animal: 'TRUE',
        Distribution: undefined,
        Energy: undefined,
        Food: 'TRUE',
        Management: undefined,
        Waste: undefined,
        Evidence: 'FALSE',
        Aim: 'take action',
        TaPerc: '68',
        GrPerc: '13',
        StatisticText: '“Fight For The Healthiest Bite”. A custom-made meal for livestock rights activists who believe in more ethical farming. It requires a strong interest in Animal and Food, supported by a delicious patty made of Sustainability. Even though it proposes a 68% of purposed-filled intentions, its main characteristic is a huge amount of groundless information, which stacks up to the 87% of the total excerpts. For healthier and happier cows, chickens and fishes.'
    },
    {  
        recipeId: 7,
        title: 'Filet-o-green sandwich',
        desc: '“Sometimes all it takes to surprise is two simple ingredients: Energy and Action. Show your commitment by consuming a creation on par to the Tree Gods.”',
        Keyword: 'energy',
        Actions: 'TRUE',
        Animal: undefined,
        Distribution: undefined,
        Energy: 'TRUE',
        Food: undefined,
        Management: undefined,
        Waste: undefined,
        Evidence: 'TRUE',
        Aim: 'take action',
        TaPerc: '66',
        GrPerc: '59',
        StatisticText: '“A Green Touch In Every Bite”. For those who love environment and composting, the Double Globe Warming Burger is here for you. Created by taking in consideration both Waste and Management, it was possible to select the most nourishing keyword as its main ingredient: Environmental. It provides your daily dose of pro-active attitude (60% take action) but with a strong lack of evidence (just 11% of contexts is providing actual data). It’s like the classic, but greener.'
    },
    {  
        recipeId: 8,
        title: 'Bio-scatter nugget burger',
        desc: '“It will make you fall in love with its incredible personality. Its best virtue? Being Natural. Don’t let its behaviour and statements let you doubt its quality.”',
        Keyword: 'natural',
        Actions: undefined,
        Animal: undefined,
        Distribution: 'TRUE',
        Energy: undefined,
        Food: 'TRUE',
        Management: undefined,
        Waste: undefined,
        Evidence: 'FALSE',
        Aim: 'dissemination',
        TaPerc: '44',
        GrPerc: '13',
        StatisticText: '“Your life will never be-o the same”. Bio-Scatter Nugget Burger will make you fall in love with its incredible personality. Distribution and Food are its most lovable characteristics. But you will get mad about it even more when you get to know its best virtue: Natural. Don’t let its 56% of disseminated behavior and 87% groundless statements let you doubt its promising quality. It will turn your life upside down.'
    }
    
   

]

let ghostRecipe={
    Keyword: 'undefined',
    Actions: 'undefined',
    Animal: 'undefined',
    Distribution: 'undefined',
    Energy: 'undefined',
    Food: 'undefined',
    Management: 'undefined',
    Waste: 'undefined',
    Evidence: 'undefined',
    Aim: 'undefined'
}
