//all recipes
const recipes = [
    {
        recipeId: 0,
        title: 'Quarter earth burger',
        desc: '“It grants educational information about the huge impact companies have on the environment and the importance of reducing it: through initiatives and business adjustments, the final goal is to be greener and eco-friendlier.”',
        Keyword: 'impact',
        Actions: 'TRUE',
        Animal: undefined,
        Distribution: undefined,
        Resources: undefined,
        Food: undefined,
        Management: 'TRUE',
        Waste: undefined,
        Evidence: 'FALSE',
        Aim: 'dissemination',
        TaPerc: '26',
        GrPerc: '4',
        StatisticText: '“This Lip-smacking Deliciousness Won’t Betray Your Planet”. Is one of your goals trying to put your heart and mind in what you believe in? Then, the Quarter Earth Pounder is the best fit for you! Its conscious recipe relies on Actions and Management, but is mainly supported by the Impact you want to make. It grants an outstanding 74% of educational information and even more overwhelming idle evidences, reaching 96% of all contexts. Hope-filled promises with not-so-clear premises.'
    },

    {
        recipeId: 1,
        title: 'Double reuse goals burger',
        desc: '“For those who love environment and composting, the recipe revolves around steps and measures which corps take to decrease their waste, whether it’s by introducing compostable single-use cutlery or reduce the amount of plastic.”',
        Keyword: 'environmental',
        Actions: undefined,
        Animal: undefined,
        Distribution: undefined,
        Resources: undefined,
        Food: undefined,
        Management: 'TRUE',
        Waste: 'TRUE',
        Evidence: 'FALSE',
        Aim: 'take action',
        TaPerc: '60',
        GrPerc: '11',
        StatisticText: 'Reuse Goals Burger is back Double”. For those who love environment and composting, this burger is here for you. Created by taking in consideration both Waste and Management, it was possible to select the most nourishing keyword as its main ingredient: Environmental. It provides your daily dose of pro-active attitude (60% take action) but with a strong lack of evidence (just 11% of contexts is providing actual data). It’s like the classic, but greener.'
    },
    {
        recipeId: 2,
        title: 'Deluxe recy-pounder',
        desc: '“It presents a dynamic approach to waste reduction and focuses on making green ideals and goals come true, through concrete actions, designed to better improve and lessen corporates’ weight on the environment.”',
        Keyword: 'environmental',
        Actions: 'TRUE',
        Animal: undefined,
        Distribution: undefined,
        Resources: undefined,
        Food: undefined,
        Management: undefined,
        Waste: 'TRUE',
        Evidence: 'FALSE',
        Aim: 'take action',
        TaPerc: '66',
        GrPerc: '15',
        StatisticText: '“Because you deserve to be recycled in the best way”. If you thrive for cleaner environment and recycling, this is the right thing for you. With the indispensable ingredient Environmental, this mixture gives the opportunity to bite Waste and Action granting you an unforgettable taste. Deluxe Recy-pounder provides to you a good amount of dynamic approach (66% take action) but as well as high percentage of groundless data (only 15% of contexts is containing accurate data). Ready to try it?'
    },
    {
        recipeId: 3,
        title: 'Smoky forest burger',
        desc: '“Fast food companies greatly depend on the quality of their menus; that is why this recipe considers how businesses are managing their ingredients and most of all how they are harvested and grown.”',
        Keyword: 'responsibility',
        Actions: undefined,
        Animal: undefined,
        Distribution: undefined,
        Resources: undefined,
        Food: 'TRUE',
        Management: 'TRUE',
        Waste: undefined,
        Evidence: 'FALSE',
        Aim: 'dissemination',
        TaPerc: '45',
        GrPerc: '14',
        StatisticText: '“Blessed by the tree gods”. Food is delicious. Sources are scarce. A win-win situation is all that we have left. Its smoky flavour was obtained by burning the finest stumps of Food and Management. Filled with high quality Responsibility, this fancy and reliable burger bestows its eaters a 55% of disseminated knowledge, but also features a slim 14% of precise analytical data. A commitment to Mother Nature and her precious soil.'
    },
    {
        recipeId: 4,
        title: 'Zero CO2 big Wrap',
        desc: '“Its uniqueness dwells in how energy sourcing is being managed by the fast food industry, in terms of carbon emissions. It shows a slow but seemingly consistent switch to renewable energies, and greater attention to the territory”',
        Keyword: 'planet',
        Actions: undefined,
        Animal: undefined,
        Distribution: undefined,
        Resources: 'TRUE',
        Food: undefined,
        Management: 'TRUE',
        Waste: undefined,
        Evidence: 'FALSE',
        Aim: 'dissemination',
        TaPerc: '48',
        GrPerc: '6',
        StatisticText: '“The Freshness Of Oxygen, Wrapped Up For You”. The freshness of the purest Planet is what makes Zero CO2 Wrap unique of its kind! The Energy Resourcing and Management-based sauce give it the flavour that has caught the attention of our customers. Plus with its 52% of dissemination statements it allows you to sustain a healthy and balanced diet without added evidence (92% groundless).'
    },

    {
        recipeId: 5,
        title: 'Spicy planet-saver wrap',
        desc: '“This recipe is all about committing to more sustainable and eco-friendlier ways of growing crops and farming animals, followed by concrete actions that improves both food quality and its way of being collected. A particular focus is put in the territory.”',
        Keyword: 'sustainability',
        Actions: 'TRUE',
        Animal: undefined,
        Distribution: undefined,
        Resources: undefined,
        Food: 'TRUE',
        Management: undefined,
        Waste: undefined,
        Evidence: 'FALSE',
        Aim: 'dissemination',
        TaPerc: '46',
        GrPerc: ' 13',
        StatisticText: '“For the hot ones”.  This seasoned combo of Food and Action are ready to burn your tongue. And if you still think it is not piquant enough, don’t worry because we prepared the spiciest ingredient of all:  Sustainability. The nourishment is granted with 54% of dissemination and incredible 87% of groundless data. Spicy Planet-saver Burger is one of the flavorsome burger you’ll ever try. Recommended by our chef Lumiere Lobster.'
    },
    {
        recipeId: 6,
        title: 'Crispy animal-welfare burger',
        desc: '“Mainly devoted to animals, this recipe focuses on the living conditions of the livestock in the intensive farms. It explores both their rights, wellbeing and exploitation: the main focus is on ethical choices regarding food sourcing.”',
        Keyword: 'sustainability',
        Actions: undefined,
        Animal: 'TRUE',
        Distribution: undefined,
        Resources: undefined,
        Food: 'TRUE',
        Management: undefined,
        Waste: undefined,
        Evidence: 'FALSE',
        Aim: 'take action',
        TaPerc: '68',
        GrPerc: '13',
        StatisticText: '“Fight For The Healthiest Bite”. A custom-made meal for livestock rights activists who believe in more ethical farming. It requires a strong interest in Animal and Food, supported by a delicious patty made of Sustainability. Even though it proposes a 68% of purposed-filled intentions, its main characteristic is a huge amount of groundless information, which stacks up to the 87% of the total excerpts. For healthier and happier cows, chickens and fishes.'
    },
    {
        recipeId: 7,
        title: 'Filet-o-green sandwich',
        desc: '“In order to show their commitment towards a greener future, companies are now providing data and studies related to resources consumption, which further concretises in sustainable initiatives taken to reduce wastage of energy sourcing.”',
        Keyword: 'energy',
        Actions: 'TRUE',
        Animal: undefined,
        Distribution: undefined,
        Resources: 'TRUE',
        Food: undefined,
        Management: undefined,
        Waste: undefined,
        Evidence: 'TRUE',
        Aim: 'take action',
        TaPerc: '66',
        GrPerc: '59',
        StatisticText: '“A Green Touch In Every Bite”. For those who love environment and composting, the Double Globe Warming Burger is here for you. Created by taking in consideration both Waste and Management, it was possible to select the most nourishing keyword as its main ingredient: Environmental. It provides your daily dose of pro-active attitude (60% take action) but with a strong lack of evidence (just 11% of contexts is providing actual data). It’s like the classic, but greener.'
    },
    {
        recipeId: 8,
        title: 'Bio-scatter nugget burger',
        desc: '“Dealing with food has its foundation in health but the next step regards its distribution. How do people can savour new meals? And most importantly, is it sustainable for the environment? This recipe examines all those measures.”',
        Keyword: 'natural',
        Actions: undefined,
        Animal: undefined,
        Distribution: 'TRUE',
        Resources: undefined,
        Food: 'TRUE',
        Management: undefined,
        Waste: undefined,
        Evidence: 'FALSE',
        Aim: 'dissemination',
        TaPerc: '44',
        GrPerc: '13',
        StatisticText: '“Your life will never be-o the same”. Bio-Scatter Nugget Burger will make you fall in love with its incredible personality. Distribution and Food are its most lovable characteristics. But you will get mad about it even more when you get to know its best virtue: Natural. Don’t let its 56% of disseminated behavior and 87% groundless statements let you doubt its promising quality. It will turn your life upside down.'
    }
]

//custom filters
let ghostRecipe = {
    Keyword: 'undefined',
    Actions: 'undefined',
    Animal: 'undefined',
    Distribution: 'undefined',
    Resources: 'undefined',
    Food: 'undefined',
    Management: 'undefined',
    Waste: 'undefined',
    Evidence: 'undefined',
    Aim: 'undefined'
}


const generalStat = [
    {
        statId: 0,
        text: "Topics are the recurring themes present in sustainability pages.",
        data: "topic",
        nOfData: 7,
        d0: "Management",
        d1: "Actions",
        d2: "Waste",
        d3: "Food",
        d4: "Resources",
        d5: "Animal",
        d6: "Distribution",
        v0: 459,
        v1: 274,
        v2: 255,
        v3: 229,
        v4: 220,
        v5: 117,
        v6: 68,
        sum: 1622
    },
    {
        statId: 1,
        text: "The custom-made green glossary includes terms which are related to environmental issues.",
        data: "keywords",
        nOfData: 23,
        d0: "Sustainability",
        d1: "Impact",
        d2: "Resources",
        d3: "Environmental",
        d4: "Planet",
        d5: "Resposibility",
        d6: "Emissions",
        d7: "Recycle",
        d8: "Green",
        d9: "Greenhouse gas",
        d10: "Deforestation",
        d11: "Climate change",
        d12: "Natural",
        d13: "Renewable energy",
        d14: "Carbon footprint",
        d15: "Single-use",
        d16: "Eco-friendly",
        d17: "Organic",
        d18: "Zero-waste",
        d19: "Reforestation",
        d20: "Preservation",
        d21: "Biodegradable",
        d22: "Net-zero",
        v0: 407,
        v1: 379,
        v2: 327,
        v3: 250,
        v4: 196,
        v5: 149,
        v6: 142,
        v7: 128,
        v8: 117,
        v9: 112,
        v10: 108,
        v11: 69,
        v12: 57,
        v13: 50,
        v14: 48,
        v15: 21,
        v16: 9,
        v17: 6,
        v18: 6,
        v19: 6,
        v20: 5,
        v21: 4,
        v22: 2,
        sum: 2598
    },
{
    statId: 2,
    text: "Aim defines whether the type of language of text excerpts is focused on facts/goals or information.",
    data: "aim",
    nOfData: 2,
    d0: "TakeAction",
    d1: "Dissemination",
    v0: 55,
    v1: 45,
    sum: 100
},
{
    statId: 3,
    text: "Evidence corresponds to the presence or lack of tangible statistical data.",
    data: "evidence",
    nOfData: 2,
    d0: "data",
    d1: "noData",
    v0: 21,
    v1: 79,
    sum: 100
}
]