const recipes = [
    {  
        recipeId: 0,
        title: 'Everything all at once',
        Keyword: undefined,
        Actions: undefined,
        Animal: undefined,
        Distribution: undefined,
        Energy: undefined,
        Food: undefined,
        Management: undefined,
        Waste: undefined,
        ToV: undefined,
        SentenceAim:undefined
    },

    {  
        recipeId: 1,
        title: 'Cristpy welfare burger',
        Keyword: 'commitment',
        Actions: undefined,
        Animal: 'TRUE',
        Distribution: undefined,
        Energy: undefined,
        Food: 'TRUE',
        Management: undefined,
        Waste: undefined,
        ToV: 'FALSE',
        SentenceAim: 'dissemination'
    },
    {  
        recipeId: 2,
        title: 'Zero CO2 big wrap',
        Keyword: 'emissions',
        Actions: undefined,
        Animal: undefined,
        Distribution: undefined,
        Energy: 'TRUE',
        Food: undefined,
        Management: 'TRUE',
        Waste: undefined,
        ToV: 'FALSE',
        SentenceAim: 'take action'
    },
    {  
        recipeId: 3,
        title: 'Double globe warming burger',
        Keyword: 'climate change',
        Actions: undefined,
        Animal: undefined,
        Distribution: undefined,
        Energy: undefined,
        Food: undefined,
        Management: 'TRUE',
        Waste: 'TRUE',
        ToV: 'TRUE',
        SentenceAim: 'take action'
    },
    {  
        recipeId: 4,
        title: 'Quarter earth pounder',
        Keyword: 'planet',
        Actions: 'TRUE',
        Animal: undefined,
        Distribution: undefined,
        Energy: undefined,
        Food: undefined,
        Management: 'TRUE',
        Waste: undefined,
        ToV: 'FALSE',
        SentenceAim:  'dissemination'
    },
    {  
        recipeId: 5,
        title: 'Smoky forest burger',
        Keyword: 'natural',
        Actions: undefined,
        Animal: undefined,
        Distribution: undefined,
        Energy: undefined,
        Food: 'TRUE',
        Management: 'TRUE',
        Waste: 'TRUE',
        ToV: 'FALSE',
        SentenceAim: 'dissemination'
    },
    {  
        recipeId: 6,
        title: 'Filet-o-green sandwich',
        Keyword: 'emissions',
        Actions: 'TRUE',
        Animal: undefined,
        Distribution: undefined,
        Energy: 'TRUE',
        Food: undefined,
        Management: undefined,
        Waste: undefined,
        ToV: 'TRUE',
        SentenceAim: 'dissemination'
    },
    {  
        recipeId: 7,
        title: 'Bio-scatter nugget burger',
        Keyword: 'sustainability',
        Actions: undefined,
        Animal: undefined,
        Distribution: 'TRUE',
        Energy: undefined,
        Food: 'TRUE',
        Management: undefined,
        Waste: undefined,
        ToV: 'FALSE',
        SentenceAim: 'take action'
    },
    {  
        recipeId: 8,
        title: 'Deluxe recy-pounder',
        Keyword: 'recycle',
        Actions: 'TRUE',
        Animal: undefined,
        Distribution: undefined,
        Energy: undefined,
        Food: undefined,
        Management: undefined,
        Waste: 'TRUE',
        ToV: 'TRUE',
        SentenceAim: 'take action'
    },
    {  
        recipeId: 9,
        title: 'Spicy planet-saver wrap',
        Keyword: 'deforestation',
        Actions: 'TRUE',
        Animal: undefined,
        Distribution: undefined,
        Energy: undefined,
        Food: 'TRUE',
        Management: undefined,
        Waste: undefined,
        ToV: 'FALSE',
        SentenceAim: 'dissemination'
    }
   

]


